import { Prisma } from "@prisma/client";
export const activities: Prisma.ActivityCreateInput[] = [
  {
    destination: "New York",
    name: "New York — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "New York",
    name: "New York — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "New York",
    name: "New York — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "New York",
    name: "New York — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "New York",
    name: "New York — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "New York",
    name: "New York — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "New York",
    name: "New York — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "New York",
    name: "New York — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "New York",
    name: "New York — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "New York",
    name: "New York — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "London",
    name: "London — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "London",
    name: "London — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "London",
    name: "London — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "London",
    name: "London — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "London",
    name: "London — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "London",
    name: "London — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "London",
    name: "London — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "London",
    name: "London — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "London",
    name: "London — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "London",
    name: "London — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Paris",
    name: "Paris — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Paris",
    name: "Paris — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Paris",
    name: "Paris — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Paris",
    name: "Paris — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Paris",
    name: "Paris — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Paris",
    name: "Paris — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Paris",
    name: "Paris — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Paris",
    name: "Paris — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Paris",
    name: "Paris — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Paris",
    name: "Paris — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Tokyo",
    name: "Tokyo — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Tokyo",
    name: "Tokyo — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Tokyo",
    name: "Tokyo — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Tokyo",
    name: "Tokyo — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Tokyo",
    name: "Tokyo — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Tokyo",
    name: "Tokyo — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Tokyo",
    name: "Tokyo — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Tokyo",
    name: "Tokyo — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Tokyo",
    name: "Tokyo — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Tokyo",
    name: "Tokyo — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Rome",
    name: "Rome — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Rome",
    name: "Rome — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Rome",
    name: "Rome — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Rome",
    name: "Rome — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Rome",
    name: "Rome — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Rome",
    name: "Rome — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Rome",
    name: "Rome — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Rome",
    name: "Rome — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Rome",
    name: "Rome — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Rome",
    name: "Rome — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Barcelona",
    name: "Barcelona — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Barcelona",
    name: "Barcelona — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Barcelona",
    name: "Barcelona — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Barcelona",
    name: "Barcelona — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Barcelona",
    name: "Barcelona — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Barcelona",
    name: "Barcelona — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Barcelona",
    name: "Barcelona — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Barcelona",
    name: "Barcelona — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Barcelona",
    name: "Barcelona — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Barcelona",
    name: "Barcelona — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Madrid",
    name: "Madrid — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Madrid",
    name: "Madrid — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Madrid",
    name: "Madrid — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Madrid",
    name: "Madrid — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Madrid",
    name: "Madrid — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Madrid",
    name: "Madrid — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Madrid",
    name: "Madrid — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Madrid",
    name: "Madrid — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Madrid",
    name: "Madrid — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Madrid",
    name: "Madrid — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Amsterdam",
    name: "Amsterdam — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Amsterdam",
    name: "Amsterdam — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Amsterdam",
    name: "Amsterdam — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Amsterdam",
    name: "Amsterdam — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Amsterdam",
    name: "Amsterdam — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Amsterdam",
    name: "Amsterdam — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Amsterdam",
    name: "Amsterdam — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Amsterdam",
    name: "Amsterdam — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Amsterdam",
    name: "Amsterdam — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Amsterdam",
    name: "Amsterdam — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Berlin",
    name: "Berlin — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Berlin",
    name: "Berlin — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Berlin",
    name: "Berlin — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Berlin",
    name: "Berlin — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Berlin",
    name: "Berlin — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Berlin",
    name: "Berlin — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Berlin",
    name: "Berlin — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Berlin",
    name: "Berlin — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Berlin",
    name: "Berlin — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Berlin",
    name: "Berlin — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Vienna",
    name: "Vienna — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Vienna",
    name: "Vienna — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Vienna",
    name: "Vienna — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Vienna",
    name: "Vienna — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Vienna",
    name: "Vienna — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Vienna",
    name: "Vienna — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Vienna",
    name: "Vienna — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Vienna",
    name: "Vienna — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Vienna",
    name: "Vienna — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Vienna",
    name: "Vienna — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Prague",
    name: "Prague — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Prague",
    name: "Prague — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Prague",
    name: "Prague — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Prague",
    name: "Prague — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Prague",
    name: "Prague — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Prague",
    name: "Prague — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Prague",
    name: "Prague — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Prague",
    name: "Prague — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Prague",
    name: "Prague — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Prague",
    name: "Prague — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Budapest",
    name: "Budapest — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Budapest",
    name: "Budapest — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Budapest",
    name: "Budapest — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Budapest",
    name: "Budapest — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Budapest",
    name: "Budapest — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Budapest",
    name: "Budapest — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Budapest",
    name: "Budapest — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Budapest",
    name: "Budapest — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Budapest",
    name: "Budapest — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Budapest",
    name: "Budapest — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Istanbul",
    name: "Istanbul — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Istanbul",
    name: "Istanbul — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Istanbul",
    name: "Istanbul — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Istanbul",
    name: "Istanbul — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Istanbul",
    name: "Istanbul — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Istanbul",
    name: "Istanbul — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Istanbul",
    name: "Istanbul — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Istanbul",
    name: "Istanbul — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Istanbul",
    name: "Istanbul — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Istanbul",
    name: "Istanbul — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Athens",
    name: "Athens — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Athens",
    name: "Athens — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Athens",
    name: "Athens — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Athens",
    name: "Athens — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Athens",
    name: "Athens — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Athens",
    name: "Athens — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Athens",
    name: "Athens — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Athens",
    name: "Athens — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Athens",
    name: "Athens — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Athens",
    name: "Athens — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Lisbon",
    name: "Lisbon — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Lisbon",
    name: "Lisbon — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Lisbon",
    name: "Lisbon — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Lisbon",
    name: "Lisbon — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Lisbon",
    name: "Lisbon — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Lisbon",
    name: "Lisbon — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Lisbon",
    name: "Lisbon — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Lisbon",
    name: "Lisbon — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Lisbon",
    name: "Lisbon — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Lisbon",
    name: "Lisbon — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dublin",
    name: "Dublin — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dublin",
    name: "Dublin — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dublin",
    name: "Dublin — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dublin",
    name: "Dublin — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dublin",
    name: "Dublin — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dublin",
    name: "Dublin — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dublin",
    name: "Dublin — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dublin",
    name: "Dublin — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dublin",
    name: "Dublin — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dublin",
    name: "Dublin — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Edinburgh",
    name: "Edinburgh — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Edinburgh",
    name: "Edinburgh — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Edinburgh",
    name: "Edinburgh — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Edinburgh",
    name: "Edinburgh — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Edinburgh",
    name: "Edinburgh — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Edinburgh",
    name: "Edinburgh — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Edinburgh",
    name: "Edinburgh — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Edinburgh",
    name: "Edinburgh — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Edinburgh",
    name: "Edinburgh — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Edinburgh",
    name: "Edinburgh — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Copenhagen",
    name: "Copenhagen — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Copenhagen",
    name: "Copenhagen — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Copenhagen",
    name: "Copenhagen — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Copenhagen",
    name: "Copenhagen — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Copenhagen",
    name: "Copenhagen — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Copenhagen",
    name: "Copenhagen — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Copenhagen",
    name: "Copenhagen — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Copenhagen",
    name: "Copenhagen — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Copenhagen",
    name: "Copenhagen — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Copenhagen",
    name: "Copenhagen — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Stockholm",
    name: "Stockholm — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Stockholm",
    name: "Stockholm — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Stockholm",
    name: "Stockholm — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Stockholm",
    name: "Stockholm — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Stockholm",
    name: "Stockholm — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Stockholm",
    name: "Stockholm — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Stockholm",
    name: "Stockholm — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Stockholm",
    name: "Stockholm — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Stockholm",
    name: "Stockholm — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Stockholm",
    name: "Stockholm — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Oslo",
    name: "Oslo — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Oslo",
    name: "Oslo — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Oslo",
    name: "Oslo — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Oslo",
    name: "Oslo — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Oslo",
    name: "Oslo — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Oslo",
    name: "Oslo — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Oslo",
    name: "Oslo — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Oslo",
    name: "Oslo — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Oslo",
    name: "Oslo — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Oslo",
    name: "Oslo — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Helsinki",
    name: "Helsinki — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Helsinki",
    name: "Helsinki — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Helsinki",
    name: "Helsinki — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Helsinki",
    name: "Helsinki — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Helsinki",
    name: "Helsinki — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Helsinki",
    name: "Helsinki — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Helsinki",
    name: "Helsinki — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Helsinki",
    name: "Helsinki — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Helsinki",
    name: "Helsinki — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Helsinki",
    name: "Helsinki — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Reykjavik",
    name: "Reykjavik — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Reykjavik",
    name: "Reykjavik — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Reykjavik",
    name: "Reykjavik — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Reykjavik",
    name: "Reykjavik — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Reykjavik",
    name: "Reykjavik — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Reykjavik",
    name: "Reykjavik — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Reykjavik",
    name: "Reykjavik — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Reykjavik",
    name: "Reykjavik — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Reykjavik",
    name: "Reykjavik — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Reykjavik",
    name: "Reykjavik — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Zurich",
    name: "Zurich — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Zurich",
    name: "Zurich — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Zurich",
    name: "Zurich — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Zurich",
    name: "Zurich — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Zurich",
    name: "Zurich — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Zurich",
    name: "Zurich — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Zurich",
    name: "Zurich — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Zurich",
    name: "Zurich — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Zurich",
    name: "Zurich — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Zurich",
    name: "Zurich — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Geneva",
    name: "Geneva — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Geneva",
    name: "Geneva — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Geneva",
    name: "Geneva — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Geneva",
    name: "Geneva — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Geneva",
    name: "Geneva — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Geneva",
    name: "Geneva — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Geneva",
    name: "Geneva — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Geneva",
    name: "Geneva — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Geneva",
    name: "Geneva — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Geneva",
    name: "Geneva — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Munich",
    name: "Munich — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Munich",
    name: "Munich — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Munich",
    name: "Munich — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Munich",
    name: "Munich — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Munich",
    name: "Munich — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Munich",
    name: "Munich — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Munich",
    name: "Munich — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Munich",
    name: "Munich — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Munich",
    name: "Munich — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Munich",
    name: "Munich — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Milan",
    name: "Milan — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Milan",
    name: "Milan — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Milan",
    name: "Milan — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Milan",
    name: "Milan — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Milan",
    name: "Milan — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Milan",
    name: "Milan — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Milan",
    name: "Milan — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Milan",
    name: "Milan — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Milan",
    name: "Milan — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Milan",
    name: "Milan — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Venice",
    name: "Venice — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Venice",
    name: "Venice — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Venice",
    name: "Venice — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Venice",
    name: "Venice — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Venice",
    name: "Venice — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Venice",
    name: "Venice — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Venice",
    name: "Venice — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Venice",
    name: "Venice — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Venice",
    name: "Venice — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Venice",
    name: "Venice — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Florence",
    name: "Florence — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Florence",
    name: "Florence — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Florence",
    name: "Florence — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Florence",
    name: "Florence — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Florence",
    name: "Florence — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Florence",
    name: "Florence — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Florence",
    name: "Florence — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Florence",
    name: "Florence — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Florence",
    name: "Florence — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Florence",
    name: "Florence — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Naples",
    name: "Naples — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Naples",
    name: "Naples — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Naples",
    name: "Naples — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Naples",
    name: "Naples — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Naples",
    name: "Naples — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Naples",
    name: "Naples — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Naples",
    name: "Naples — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Naples",
    name: "Naples — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Naples",
    name: "Naples — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Naples",
    name: "Naples — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dubrovnik",
    name: "Dubrovnik — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dubrovnik",
    name: "Dubrovnik — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dubrovnik",
    name: "Dubrovnik — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dubrovnik",
    name: "Dubrovnik — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dubrovnik",
    name: "Dubrovnik — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dubrovnik",
    name: "Dubrovnik — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dubrovnik",
    name: "Dubrovnik — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dubrovnik",
    name: "Dubrovnik — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dubrovnik",
    name: "Dubrovnik — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dubrovnik",
    name: "Dubrovnik — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Split",
    name: "Split — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Split",
    name: "Split — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Split",
    name: "Split — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Split",
    name: "Split — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Split",
    name: "Split — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Split",
    name: "Split — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Split",
    name: "Split — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Split",
    name: "Split — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Split",
    name: "Split — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Split",
    name: "Split — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Zagreb",
    name: "Zagreb — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Zagreb",
    name: "Zagreb — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Zagreb",
    name: "Zagreb — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Zagreb",
    name: "Zagreb — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Zagreb",
    name: "Zagreb — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Zagreb",
    name: "Zagreb — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Zagreb",
    name: "Zagreb — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Zagreb",
    name: "Zagreb — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Zagreb",
    name: "Zagreb — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Zagreb",
    name: "Zagreb — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Belgrade",
    name: "Belgrade — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Belgrade",
    name: "Belgrade — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Belgrade",
    name: "Belgrade — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Belgrade",
    name: "Belgrade — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Belgrade",
    name: "Belgrade — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Belgrade",
    name: "Belgrade — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Belgrade",
    name: "Belgrade — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Belgrade",
    name: "Belgrade — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Belgrade",
    name: "Belgrade — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Belgrade",
    name: "Belgrade — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Sofia",
    name: "Sofia — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Sofia",
    name: "Sofia — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Sofia",
    name: "Sofia — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Sofia",
    name: "Sofia — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Sofia",
    name: "Sofia — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Sofia",
    name: "Sofia — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Sofia",
    name: "Sofia — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Sofia",
    name: "Sofia — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Sofia",
    name: "Sofia — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Sofia",
    name: "Sofia — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bucharest",
    name: "Bucharest — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bucharest",
    name: "Bucharest — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bucharest",
    name: "Bucharest — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bucharest",
    name: "Bucharest — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bucharest",
    name: "Bucharest — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bucharest",
    name: "Bucharest — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bucharest",
    name: "Bucharest — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bucharest",
    name: "Bucharest — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bucharest",
    name: "Bucharest — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bucharest",
    name: "Bucharest — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Krakow",
    name: "Krakow — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Krakow",
    name: "Krakow — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Krakow",
    name: "Krakow — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Krakow",
    name: "Krakow — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Krakow",
    name: "Krakow — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Krakow",
    name: "Krakow — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Krakow",
    name: "Krakow — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Krakow",
    name: "Krakow — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Krakow",
    name: "Krakow — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Krakow",
    name: "Krakow — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Warsaw",
    name: "Warsaw — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Warsaw",
    name: "Warsaw — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Warsaw",
    name: "Warsaw — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Warsaw",
    name: "Warsaw — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Warsaw",
    name: "Warsaw — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Warsaw",
    name: "Warsaw — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Warsaw",
    name: "Warsaw — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Warsaw",
    name: "Warsaw — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Warsaw",
    name: "Warsaw — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Warsaw",
    name: "Warsaw — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Brussels",
    name: "Brussels — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Brussels",
    name: "Brussels — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Brussels",
    name: "Brussels — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Brussels",
    name: "Brussels — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Brussels",
    name: "Brussels — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Brussels",
    name: "Brussels — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Brussels",
    name: "Brussels — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Brussels",
    name: "Brussels — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Brussels",
    name: "Brussels — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Brussels",
    name: "Brussels — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bruges",
    name: "Bruges — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bruges",
    name: "Bruges — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bruges",
    name: "Bruges — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bruges",
    name: "Bruges — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bruges",
    name: "Bruges — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bruges",
    name: "Bruges — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bruges",
    name: "Bruges — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bruges",
    name: "Bruges — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bruges",
    name: "Bruges — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bruges",
    name: "Bruges — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Luxembourg City",
    name: "Luxembourg City — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Luxembourg City",
    name: "Luxembourg City — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Luxembourg City",
    name: "Luxembourg City — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Luxembourg City",
    name: "Luxembourg City — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Luxembourg City",
    name: "Luxembourg City — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Luxembourg City",
    name: "Luxembourg City — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Luxembourg City",
    name: "Luxembourg City — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Luxembourg City",
    name: "Luxembourg City — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Luxembourg City",
    name: "Luxembourg City — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Luxembourg City",
    name: "Luxembourg City — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dubai",
    name: "Dubai — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dubai",
    name: "Dubai — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dubai",
    name: "Dubai — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dubai",
    name: "Dubai — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dubai",
    name: "Dubai — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dubai",
    name: "Dubai — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dubai",
    name: "Dubai — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dubai",
    name: "Dubai — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dubai",
    name: "Dubai — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Dubai",
    name: "Dubai — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Abu Dhabi",
    name: "Abu Dhabi — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Abu Dhabi",
    name: "Abu Dhabi — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Abu Dhabi",
    name: "Abu Dhabi — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Abu Dhabi",
    name: "Abu Dhabi — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Abu Dhabi",
    name: "Abu Dhabi — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Abu Dhabi",
    name: "Abu Dhabi — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Abu Dhabi",
    name: "Abu Dhabi — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Abu Dhabi",
    name: "Abu Dhabi — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Abu Dhabi",
    name: "Abu Dhabi — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Abu Dhabi",
    name: "Abu Dhabi — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Doha",
    name: "Doha — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Doha",
    name: "Doha — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Doha",
    name: "Doha — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Doha",
    name: "Doha — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Doha",
    name: "Doha — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Doha",
    name: "Doha — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Doha",
    name: "Doha — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Doha",
    name: "Doha — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Doha",
    name: "Doha — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Doha",
    name: "Doha — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Singapore",
    name: "Singapore — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Singapore",
    name: "Singapore — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Singapore",
    name: "Singapore — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Singapore",
    name: "Singapore — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Singapore",
    name: "Singapore — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Singapore",
    name: "Singapore — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Singapore",
    name: "Singapore — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Singapore",
    name: "Singapore — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Singapore",
    name: "Singapore — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Singapore",
    name: "Singapore — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Hong Kong",
    name: "Hong Kong — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Hong Kong",
    name: "Hong Kong — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Hong Kong",
    name: "Hong Kong — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Hong Kong",
    name: "Hong Kong — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Hong Kong",
    name: "Hong Kong — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Hong Kong",
    name: "Hong Kong — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Hong Kong",
    name: "Hong Kong — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Hong Kong",
    name: "Hong Kong — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Hong Kong",
    name: "Hong Kong — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Hong Kong",
    name: "Hong Kong — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Seoul",
    name: "Seoul — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Seoul",
    name: "Seoul — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Seoul",
    name: "Seoul — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Seoul",
    name: "Seoul — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Seoul",
    name: "Seoul — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Seoul",
    name: "Seoul — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Seoul",
    name: "Seoul — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Seoul",
    name: "Seoul — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Seoul",
    name: "Seoul — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Seoul",
    name: "Seoul — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bangkok",
    name: "Bangkok — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bangkok",
    name: "Bangkok — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bangkok",
    name: "Bangkok — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bangkok",
    name: "Bangkok — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bangkok",
    name: "Bangkok — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bangkok",
    name: "Bangkok — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bangkok",
    name: "Bangkok — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bangkok",
    name: "Bangkok — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bangkok",
    name: "Bangkok — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Bangkok",
    name: "Bangkok — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Kuala Lumpur",
    name: "Kuala Lumpur — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Kuala Lumpur",
    name: "Kuala Lumpur — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Kuala Lumpur",
    name: "Kuala Lumpur — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Kuala Lumpur",
    name: "Kuala Lumpur — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Kuala Lumpur",
    name: "Kuala Lumpur — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Kuala Lumpur",
    name: "Kuala Lumpur — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Kuala Lumpur",
    name: "Kuala Lumpur — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Kuala Lumpur",
    name: "Kuala Lumpur — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Kuala Lumpur",
    name: "Kuala Lumpur — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Kuala Lumpur",
    name: "Kuala Lumpur — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Sydney",
    name: "Sydney — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Sydney",
    name: "Sydney — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Sydney",
    name: "Sydney — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Sydney",
    name: "Sydney — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Sydney",
    name: "Sydney — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Sydney",
    name: "Sydney — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Sydney",
    name: "Sydney — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Sydney",
    name: "Sydney — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Sydney",
    name: "Sydney — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Sydney",
    name: "Sydney — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Melbourne",
    name: "Melbourne — Historic Center Walking Tour",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Melbourne",
    name: "Melbourne — Main Cathedral / Landmark Visit",
    type: "culture",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Melbourne",
    name: "Melbourne — Top Museum Highlights",
    type: "culture",
    durationHours: 2,
    priceLevel: 3,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Melbourne",
    name: "Melbourne — Local Food Market Tasting",
    type: "gastronomy",
    durationHours: 2,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Melbourne",
    name: "Melbourne — Signature Street Food Crawl",
    type: "gastronomy",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Melbourne",
    name: "Melbourne — City Park & Gardens Stroll",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Melbourne",
    name: "Melbourne — Panoramic Viewpoint / Sunset Spot",
    type: "nature",
    durationHours: 1,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Melbourne",
    name: "Melbourne — Riverfront / Harbor Walk",
    type: "nature",
    durationHours: 2,
    priceLevel: 1,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Melbourne",
    name: "Melbourne — Evening Entertainment District",
    type: "entertainment",
    durationHours: 3,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
  {
    destination: "Melbourne",
    name: "Melbourne — Day Trip Essentials (nearby)",
    type: "entertainment",
    durationHours: 4,
    priceLevel: 2,
    latitude: null,
    longitude: null,
  },
];
